### ISSUE TITLE
一些旧版本都有淘宝的链接，最新版已更新至2.15.1

### ISSUE THREAD

**Issue by zhihaofans** [waylau/git-for-win#3]
`2.8.4`, `2.9.0`, `2.9.2`, `2.10.0`, `2.11.0`可以换成 `npm.taobao.org` 的链接

最新版已更新至`2.15.1`

**Comment by waylau** [comment]
@zhihaofans  感谢您的反馈。已经更新至 v2.15.1.windows.2。

本站只维护最新版本的Git。
