### ISSUE TITLE
where is the 32-bit?

### ISSUE THREAD

**Issue by glgoo** [waylau/git-for-win#8]
Please add 32 bit!

**Comment by waylau** [comment]
replace the 64-bit url to 32-bit, for example 
,change <https://npm.taobao.org/mirrors/git-for-windows/v2.19.1.windows.1/Git-2.19.1-64-bit.exe>
to  <https://npm.taobao.org/mirrors/git-for-windows/v2.19.1.windows.1/Git-2.19.1-32-bit.exe>
